import { Item, Recipe } from '../types';

const ENCH_MULT: Record<string, number> = { '0': 1, '1': 2, '2': 4, '3': 8, '4': 16 };

const TRUE_BASE_FAME: Record<string, number> = {
  'T4': 22.5,
  'T5': 90,
  'T6': 270,
  'T7': 645,
  'T8': 1395,
};

const TRUE_JOURNAL_CAPACITY: Record<string, number> = {
  'T4': 3600,
  'T5': 7200,
  'T6': 14400,
  'T7': 28800,
  'T8': 57600,
};

export function calculateJournalsFilled(recipe: Recipe, item: Item): number {
  if (!recipe.journalId) return 0;
  
  // Calculate total non-artifact materials used
  const baseResourceAmount = recipe.materials.reduce((acc, mat) => acc + (mat.itemId.includes('ARTIFACT') ? 0 : mat.amount), 0);
  
  // Calculate the true fame generated by crafting this item (1x)
  const fameGenerated = baseResourceAmount * (TRUE_BASE_FAME[item.tier] || 0) * (ENCH_MULT[item.enchantment] || 1);
  
  // Get the journal capacity for the item's tier
  const journalCapacity = TRUE_JOURNAL_CAPACITY[item.tier] || 1;
  
  return fameGenerated / journalCapacity;
}
